<?php
if ( !function_exists('wi_social_array') ) {
function wi_social_array(){
	return array(
		'facebook'		=>	__('Facebook','wi'),
		'twitter'		=>	__('Twitter','wi'),
		'google-plus'	=>	__('Google+','wi'),
		'linkedin'	 	=>	__('LinkedIn','wi'),
		'tumblr'	 	=>	__('Tumblr','wi'),
		'pinterest'	 	=>	__('Pinterest','wi'),
		'youtube'	 	=>	__('YouTube','wi'),
		'skype'	 		=>	__('Skype','wi'),
		'instagram'	 	=>	__('Instagram','wi'),
		'delicious'	 	=>	__('Delicious','wi'),
		'reddit'		=>	__('Reddit','wi'),
		'stumbleupon'	=>	__('StumbleUpon','wi'),
		'wordpress'	 	=>	__('Wordpress','wi'),
		'joomla'		=>	__('Joomla','wi'),
		'blogger'	 	=>	__('Blogger','wi'),
		'vimeo'	 		=>	__('Vimeo','wi'),
		'yahoo'	 		=>	__('Yahoo!','wi'),
		'flickr'	 	=>	__('Flickr','wi'),
		'picasa'	 	=>	__('Picasa','wi'),
		'deviantart'	=>	__('DeviantArt','wi'),
		'github'	 	=>	__('GitHub','wi'),
		'stackoverflow'	=>	__('StackOverFlow','wi'),
		'xing'	 		=>	__('Xing','wi'),
		'flattr'	 	=>	__('Flattr','wi'),
		'foursquare'	=>	__('Foursquare','wi'),
		'paypal'	 	=>	__('Paypal','wi'),
		'yelp'	 		=>	__('Yelp','wi'),
		'soundcloud'	=>	__('SoundCloud','wi'),
		'lastfm'	 	=>	__('Last.fm','wi'),
		'lanyrd'	 	=>	__('Lanyrd','wi'),
		'dribbble'	 	=>	__('Dribbble','wi'),
		'forrst'	 	=>	__('Forrst','wi'),
		'steam'	 		=>	__('Steam','wi'),
		'behance'		=>	__('Behance','wi'),
		'mixi'			=>	__('Mixi','wi'),
		'weibo'			=>	__('Weibo','wi'),
		'renren'		=>	__('Renren','wi'),
		'evernote'		=>	__('Evernote','wi'),
		'dropbox'		=>	__('Dropbox','wi'),
		'bitbucket'		=>	__('Bitbucket','wi'),
		'trello'		=>	__('Trello','wi'),
		'vk'			=>	__('VKontakte','wi'),
		'home'			=>	__('Homepage','wi'),
		'envelope-alt'	=>	__('Email','wi'),
		'rss'			=>	__('RSS','wi'),
	);
}
}